Shili/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('post/', include('post.urls')),
    path('profile/', include('user.urls')),
    path('chat/', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'
urlpatterns = [
    path('', views.BoxChat.as_view(), name='box'),
    path('save_mess/', views.SaveMess.as_view(), name='save_mess'),
    path('delete_mess/', views.DeleteMess.as_view(), name='delete_mess'),
]

home/urls.py
from django.urls import path
from home import views

app_name = 'home'
urlpatterns = [
    path('', views.Index.as_view(), name='home'),
    path('test', views.Test.as_view(), name='test'),
    path('login/', views.Login_user.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.Register_user.as_view(), name='register'),
    path('sendpass/', views.Send_pass.as_view(), name='sendpass'),
    path('xacthuc/', views.Xac_thuc.as_view(), name='Xac_thuc'),
    path('xacthuc/<str:key>/<str:ban_ma>', views.Xacthuc.as_view(), name='xacthuc'),
    path('resetpassword/<str:key>/<str:ban_ma>', views.ResetPassword.as_view(), name='resetpassword'),
    path('check/', views.Check.as_view(), name='check'),
    # ==================
    # path('api/get_content/', views.ApiGetContent.as_view(), name='api_get_content'),
]

post/urls.py
from django.urls import path
from post import views

app_name = 'post'
urlpatterns = [
    path('', views.TopHashtagPost.as_view(), name='TopHashtagPost'),
    path('<int:post_id>/', views.ShowPost.as_view(), name='ShowPost'),
    path('edit/<int:post_id>', views.EditPost.as_view(), name='edit'),
    path('set_post/', views.SetPost.as_view(), name='set_post'),
    path('delete/<int:post_id>', views.DeletePost.as_view(), name='delete_post'),
    path('hashtag/<str:hashtag>', views.OneHashtag.as_view(), name='api_hashtag_post'),
    path('hashtag/', views.TopHashtagPost.as_view(), name='TopHashtagPost'),
    path('comments/', views.Comment_post.as_view(), name='comments'),
    path('delete_comment/', views.Delete_comment.as_view(), name='delete_comment'),
    path('api/top_hashtag/', views.ApiTopHashtag.as_view(), name='top_hashtag'),
]

user/urls.py
from django.urls import path
from user import views

app_name = 'user'
urlpatterns = [
    path('add_follow/', views.Add_follow.as_view(), name='add_follow'),
    path('alluser/', views.AllUser.as_view(), name='all_user'),
    path('<str:user_username>', views.Profile.as_view(), name='profile'),
    path('', views.ProfileMain.as_view(), name='profile_main'),
    path('api/getprofile/', views.ApiGetProfile.as_view(), name='api_getprofile'),
    path('api/editprofile/', views.ApiEditProfile.as_view(), name='edit_profile'),
    path('api/editavbg/', views.Edit_av_bg.as_view(), name='edit_av_bg'),
    path('api/your_friend/', views.ApiYourFriend.as_view(), name='api_your_friend'),
]

home/views.py
import os
import re
from datetime import date

import requests
from bs4 import BeautifulSoup
from django.contrib.auth import authenticate, login, logout

from django.core.mail import send_mail
from django.forms import model_to_dict
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
import json
# Create your views here.
from django.views import View

from home.models import ShiliEmail, MaHoaOneTimePad, Database, CrawlPage
from post.models import Post, Comment

from user.models import MyUser, Follower
from django.core.files import File


class Test(View):
    def get(self, request):
        today = str(date.today())
        module_dir = os.path.dirname(__file__)
        file_path = os.path.join(module_dir, 'stactic/mail/data.txt')
        with open(file_path) as json_file:
            data = json.load(json_file)
        dater = data[len(data) - 1]["today"]
        if dater != today:
            Crawl = CrawlPage()
            data = Crawl.crawNewsData('https://tuoitre.vn', 'https://tuoitre.vn/tin-moi-nhat.htm')
            data.append({"today": str(today)})
            with open(file_path, 'w') as outfile:
                json.dump(data, outfile)
        with open(file_path) as json_file:
            data = json.load(json_file)
        data = data[:len(data) - 1]
        return render(request, 'home/lacx.html', {'data': data})


class Index(View):
    def get(self, request):
        if request.user.is_authenticated:
            database = Database()
            kt = database.get_watching(request.user.username)
            if kt:
                a = Follower.objects.filter(main_user=int(request.user.id)).values('followres')
                x = [i["followres"] for i in a] + [request.user.id]
                x = Post.objects.filter(user__id__in=x).exclude(public="Chỉ Mình Tôi").order_by('-created_at')
                out = Database().convert_post(x)
                # return JsonResponse(out, safe=False)
                return render(request, 'home/home.html', {'posts': out, 'page': 'Trang chủ Shili'})
            else:
                return render(request, 'user/all_user.html', {'page': 'all_user'})
        else:
            return render(request, 'home/index.html')


class Login_user(View):
    def post(self, request):
        if request.method == 'POST':
            password = request.POST.get('password')
            username = request.POST.get('username')
            try:
                user = authenticate(username=MyUser.objects.get(email=username), password=password)
            except:
                user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('home:home')
            else:
                err = [
                    'Thông tin đăng nhập không chính xác hoặc tài khoản này chưa được kích hoạt. Vui lòng kiểm tra lại']
                print(username)
                return render(request, 'home/index.html',
                              {'username': username, 'password': password, 'err': err, 'themes': 'login'})


def logout_user(request):
    try:
        logout(request)
    except:
        pass
    return redirect('home:home')


class Register_user(View):
    def post(self, request):
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        new_user = MyUser()
        new_user.first_name = request.POST.get('first_name')
        new_user.last_name = request.POST.get('last_name')
        new_user.username = request.POST.get('username')
        new_user.email = request.POST.get('email')
        new_user.email = request.POST.get('email')
        new_user.birthday = request.POST.get('birthday')
        new_user.gender = request.POST.get('gender')
        password = {'password1': password1, 'password2': password2, }
        err = []
        x = True
        if MyUser.objects.filter(username=new_user.username):
            x = x and False
            err.append('Username này đã tồn tại trong hệ thống, xin thử lại')
        if MyUser.objects.filter(email=new_user.email):
            x = x and False
            err.append('Địa chỉ email đã tồn tại trong hệ thống, Hãy check email khác')
        if not x:
            return render(request, 'home/index.html',
                          {'newuser': new_user, 'password': password, 'themes': 'register',
                           'err': err})
        else:
            email = new_user.email
            new_user.set_password(password1)
            new_user.is_active = 0
            new_user.save()
            one_time_pad = MaHoaOneTimePad()
            result = one_time_pad.ma_hoa(email)
            domain = request.scheme + '://' + request.META['HTTP_HOST']
            url = domain + '/xacthuc/' + result[0] + '/' + result[1]
            content = "We're excited to have you get started. First, you need to confirm your account. Just press the button below."
            theme = ShiliEmail()
            msg_html = theme.form_mail(url, content, email)
            send_mail("Welcome to Shili!", "Hello", "PLC", [email], html_message=msg_html, fail_silently=False)
            err.append('Đăng kí thành công tài khoản. Kiểm tra email để nhận liên kết kích hoạt tài khoản')
            # return render(request, 'home/index.html', {'themes': 'register',  'err': err})
            return redirect('home:test')


class Send_pass(View):
    def post(self, request):
        email = request.POST.get('email')
        if MyUser.objects.filter(email=email).exists():
            one_time_pad = MaHoaOneTimePad()
            result = one_time_pad.ma_hoa(email)
            mail_content = "Hello"
            mail_title = "Shili! Đặt lại mật khẩu"
            domain = request.scheme + '://' + request.META['HTTP_HOST']
            url = domain + '/resetpassword/' + result[0] + '/' + result[1]
            content = "If did not make this request, just ignore this  email. Otherwise, please click the button below to change your password:"
            theme = ShiliEmail()
            msg_html = theme.form_mail(url, content, email, 'xacthuc')
            send_mail(mail_title, mail_content, "PLC", [email], html_message=msg_html, fail_silently=False)
            return HttpResponse('Kiểm tra email để lấy liên kết đến trang thay đổi mật khẩu')
        err = ['Email này không tồn tại trong hệ thống,vui lòng kiểm tra lại']
        return render(request, 'home/index.html', {'email': email, 'themes': 'forgotPass', 'err': err})


class Xac_thuc(View):
    def post(self, request):
        email = request.POST.get('email')
        if MyUser.objects.filter(email=email):
            one_time_pad = MaHoaOneTimePad()
            result = one_time_pad.ma_hoa(email)
            mail_content = "Hello"
            mail_title = "Shili! Xác thực tài khoản"
            domain = request.scheme + '://' + request.META['HTTP_HOST']
            url = domain + '/xacthuc/' + result[0] + '/' + result[1]
            content = "We're excited to have you get started. First, you need to confirm your account. Just press the button below."
            theme = ShiliEmail()
            msg_html = theme.form_mail(url, content, email)
            send_mail(mail_title, mail_content, "PLC", [email], html_message=msg_html, fail_silently=False)
            return render(request, 'home/index.html', {'email': email, 'themes': 'kich_hoat', 'err': [
                'Kiểm tra email để lấy liên kết đến trang xác thực tài khoản']})
        return render(request, 'home/index.html', {'email': email, 'themes': 'kich_hoat', 'err': [
            'Email này không tồn tại trong hệ thống, vui lòng kiểm tra lại']})


class Xacthuc(View):
    def get(self, request, key, ban_ma):
        one_time_pad = MaHoaOneTimePad()
        email = one_time_pad.giai_ma(key, ban_ma)
        context = {
            'email': email,
            'key': key,
            'ban_ma': ban_ma,
        }
        user = MyUser.objects.get(email=email)
        user.is_active = 1
        user.save()
        return render(request, 'mail/xacthuc.html', context)


class ResetPassword(View):
    def get(self, request, key, ban_ma):
        one_time_pad = MaHoaOneTimePad()
        email = one_time_pad.giai_ma(key, ban_ma)
        context = {
            'email': email,
            'key': key,
            'ban_ma': ban_ma,
        }
        return render(request, 'mail/reset_password.html', context)

    def post(self, request, key, ban_ma):
        one_time_pad = MaHoaOneTimePad()
        email = one_time_pad.giai_ma(key, ban_ma)
        mk1 = request.POST.get('password1')
        mk2 = request.POST.get('password2')
        check = {}
        check["mk1"] = mk1
        check["mk2"] = mk2

        x = re.search("^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$", mk1)
        if x:
            if mk1 == mk2:
                edit_user = MyUser.objects.get(email=email)
                edit_user.set_password(mk1)
                edit_user.save()
                check["true"] = True
            else:
                check["khopMK"] = False
        else:
            check["domanhMK"] = False
        context = {
            'email': email,
            'key': key,
            'ban_ma': ban_ma,
            'check': check,
        }
        return render(request, 'mail/reset_password.html', context)


class Check(View):
    def post(self, request):
        data = json.loads(request.body.decode('utf-8'))
        username = data['username']
        email = data['email']
        try:
            MyUser.objects.get(username=username)
            return HttpResponse('Username đã tồn tại trong hệ thống vui lòng thử username mới')
        except:
            pass
        try:
            MyUser.objects.get(email=email)
            return HttpResponse('Địa chỉ email đã tồn tại trong hệ thống, Hãy check email khác')
        except:
            pass
        return HttpResponse('')


# class ApiGetContent(View):

templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}{{ page }} {{ hashtag_post|upper }} {{ post_id }}{% endblock %}
{% block data %}
    <div style="display:none" id="data_post" hashtag_post="{{ hashtag_post }}" post_id="{{ post_id }}"
    ></div>
{% endblock data %}
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
{% block noidung %}
    {% if posts %}
        {% for i in posts %}
            <div class="baidang mb-5">
                <div class="post_thongtin">
                    {% if i.avatar %}
                        <img src="/media/{{ i.avatar }}" class="post_avatar"
                             alt="{{ i.avatar }}" alt="">
                    {% else %}
                        <img src="{% static 'user/images/avatar.png' %}" class="post_avatar"
                             alt="avatar">
                    {% endif %}
                    <div>
                        <div>
                            <a class="post_name" href="{% url 'user:profile' i.username %}">
                                {{ i.first_name }} {{ i.last_name }}
                            </a>
                            <label class="post_feeling"><i
                                    class="fas fa-check-circle"></i> {{ i.feeling }}</label>
                        </div>
                        <div>
                            <a class="post_time" href="{% url 'post:ShowPost' i.post %}">{{ i.created_at }}</a>
                            <label class="post_public"><i
                                    class="fas fa-globe-europe"> </i> {{ i.public }}</label>
                        </div>
                    </div>
                    {% if i.user == user.id %}
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end  dropdown-menu-dark "
                                aria-labelledby="dropdownMenuButton">
                                <a style="color:#ffffff" href="{% url 'post:edit' i.post %}">
                                    <li>Chỉnh sửa bài viết</li>
                                </a>
                                <a style="color:#ffffff" href="{% url 'post:delete_post' i.post %}">
                                    <li>Xóa bài viết này</li>
                                </a>
                            </ul>
                        </div>
                    {% endif %}
                </div>
                <div class="post_content">{{ i.content }}</div>
                <a class="post_hashtag" href="{% url 'post:api_hashtag_post' i.hashtag %}">
                    <i class="fas fa-hashtag"></i>{{ i.hashtag }} </a>
                {% if i.photo %}
                    <img src="/media/{{ i.photo }}" class="post_image"
                         alt="{{ i.photo }}">
                {% endif %}

                <input type="text" v-model="comment[{{ forloop.counter0 }}]"
                       @keyup.enter="comment_func({{ i.post }},{{ forloop.counter0 }})"
                       class="col-12 px-4 py-2 cmt_input"
                       placeholder="Để lại bình luận của bạn">

                <div class="comment container row p-2 my-3 mx-3 col-11" v-if="comment_data[{{ forloop.counter0 }}]"
                     v-for="key in comment_data[{{ forloop.counter0 }}]" :key="key.comment">
                    <div class="col-12">
                        <a class="comment_name" :href="domain + `/profile/${ key.username}`">
                            [[key.first_name + " " +key.last_name]]</a>
                        <small class="mx-3"><i class="far fa-clock"></i> [[key.created_at]]</small>
                        <i v-if="user_id == key.id " @click="comment_delete_func({{ i.post }},key.comment,i)"
                           class="fas fa-trash-alt remove_cmt"></i>
                    </div>
                    <div class="col-12 content_cmt">[[key.content]]</div>
                </div>
                <div class="show_cmt mt-3 mx-3 col-12" @click="comment_show_func({{ i.post }},{{ forloop.counter0 }})">
                    <i class="fas fa-share"></i> Hiển thị bình luận
                </div>
            </div>

        {% endfor %}
    {% else %}
        <div class="user_follow">
            <h3>Hi {{ user.last_name }}, có vẻ như dữ liệu mà bạn yêu cầu đã không còn tồn tại nữa. </h3>
            <hr>
            <a style="text-align: center" href="{% url 'home:home' %}">
                <h5><i class="fas fa-home "></i>&ensp; Trở lại trang chính</h5>
            </a>
            <hr>
        </div>
    {% endif %}
    <h5 style="color:#f5f5f5;">Hi {{ user.last_name }} ! Không còn bài viết nào khác hãy theo dõi
        mọi người để tiếp
        cận thêm nhiều bài viết nữa</h5>
{% endblock noidung %}

templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Shili - Social Network{% endblock %}</title>
    <link rel="icon" href="{% static 'images/shili.png' %}" type="image/gif">
    <script type="text/javascript" src="https://code.jquery.com/jquery-latest.pack.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-latest.pack.js"></script>
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <style>


    </style>
</head>

<body>
{% if themes %}
    <div style="display:none" id="themes" themes="'{{ themes }}'">{{ themes }}</div>
{% endif %}
<div id="index_login">
    <div class="bar">
        {#        <ul>#}
        {#            <li>VLau</li>#}
        {#            <li>VLau</li>#}
        {#            <li>VLau</li>#}
        {#        </ul>#}
    </div>
    <div class="main">
        <div class="text">
            <h1>WELCOME TO <span>Shili</span></h1>
            <p>Bắt trọn khoảnh khắc - Dẫn dắt xu hướng </p>
            <button class="button" @mouseover="themes='register'" @click="login_bg=!login_bg">Join now</button>
            <button class="button" @mouseover="themes='login'" @click="login_bg=!login_bg">Sign in</button>
            <form action="#intro">
                <input class="button" type="submit" value="About us"/>
            </form>
        </div>
        <img src="{% static 'images/Multimedia.png' %}" alt="...">
    </div>

    <div id="intro" class="">
        <img src="{% static 'images/Form.png' %}" class="d-block w-100" alt="...">
        <div class="text">
            <h2>Tầm nhìn</h2>
            <template v-for="item in  intro">
                <h4>{{ i.title }}</h4>
                <div class="card">
                    <h5 class="title">[[item.title]] </h5>
                    <p class="card-text"> &emsp; &emsp;
                        [[item.content]]
                        <a :href="item.href">[[item.link]]</a>
                    </p>
                </div>
            </template>
        </div>
    </div>
    {#background#}
    <transition name="login" enter-active-class="animate__animated bg"
                leave-active-class="animate__animated bgout">
        <template v-if="login_bg ">
            <div class="bg_login" @click="login_bg=!login_bg "></div>
        </template>
    </transition>
    <transition name="login" enter-active-class="animate__animated animate__zoomInDown"
                leave-active-class="animate__animated animate__bounceOutRight">
        <div class="join" v-if="login_bg">
            <div class="login">
                <template v-if="themes == 'login' || themes == 'kich_hoat'|| themes == 'forgotPass'|| themes == 1 ">
                    <img src="{% static 'images/cryptocurrency.png' %}" alt="...">
                </template>
                <transition name="login1" enter-active-class="animate__animated animate__fadeInLeft"
                            leave-active-class="animate__animated animate__fadeOutRight">
                    <template v-if="themes === 'login'">

                        <div class="form">
                            <h2>Đăng Nhập</h2>
                            <div class="field">
                                <form action="{% url 'home:login' %}" enctype="multipart/form-data" method="post">
                                    {% csrf_token %}
                                    <input type="text" name="username" value="{{ username }}"
                                           placeholder="Tên đăng nhập hoặc email">
                                    <input type="password" name="password" value="{{ password }}"
                                           placeholder="Mật khẩu">
                                    <h6 class="my-4  thong_bao"> [[login.result]]</h6>
                                    <div>
                                        <small @click="chuyen('forgotPass')">Quên mật khẩu?</small>
                                        <small @click="chuyen('kich_hoat')">Kích hoạt tài khoản</small>
                                    </div>
                                    {% for i in err %}
                                        <h4 class="my-4  thong_bao"> {{ i }}</h4>
                                    {% endfor %}
                                    <button class="button" type="submit">Đăng Nhập</button>
                                </form>
                            </div>
                        </div>
                    </template>
                </transition>
                <transition name="forgotPass" enter-active-class="animate__animated animate__fadeInLeft"
                            leave-active-class="animate__animated animate__fadeOutRight">
                    <template v-if="themes === 'forgotPass'">
                        <div class="form ">
                            <h2>Quên Mật Khẩu</h2>
                            <form class="field" action="{% url 'home:sendpass' %}" enctype="multipart/form-data"
                                  method="post">
                                {% csrf_token %}
                                <input type="email" name="email" value="{{ email }}" placeholder="Email" required>
                                {% for i in err %}
                                    <h4 class="my-4  thong_bao"> {{ i }}</h4>
                                {% endfor %}
                                <button class="button" type="submit">Lấy lại mật khẩu</button>
                                <small class="col-12" @click="chuyen('login')"> Trở lại</small>
                            </form>
                        </div>
                    </template>
                </transition>
                <transition name="kich_hoat" enter-active-class="animate__animated animate__fadeInLeft"
                            leave-active-class="animate__animated animate__fadeOutRight">
                    <template v-if="themes === 'kich_hoat'">
                        <div class="form">
                            <h2>Kích hoạt tài khoản</h2>
                            <div>
                                <form class="field" action="{% url 'home:Xac_thuc' %}" enctype="multipart/form-data"
                                      method="post">
                                    {% csrf_token %}
                                    <input type="email" name="email" value="{{ email }}" placeholder="Nhập email">
                                    {% for i in err %}
                                        <h4 class="my-4  thong_bao"> {{ i }}</h4>
                                    {% endfor %}
                                    <button class="button" type="submit">Kích hoạt tài khoản</button>
                                </form>
                            </div>
                            <small class="col-12" @click="chuyen('login')"> Trở lại</small>
                        </div>
                    </template>
                </transition>
            </div>
            <transition name="register" enter-active-class="animate__animated animate__zoomInDown"
                        leave-active-class="animate__animated animate__bounceOutRight">
                <div>
                    <div v-if="themes === 'register'" class=" register">
                        <div class="form">
                            <h2>Đăng ký</h2>

                            <form class="field" action="{% url 'home:register' %}" enctype="multipart/form-data"
                                  method="post">
                                {% csrf_token %}
                                <input class="chia" type="text" name="first_name" value="{{ newuser.first_name }}"
                                       placeholder="Họ" required>
                                <input class="chia" type="text" name="last_name" value="{{ newuser.last_name }}"
                                       placeholder="Tên" required>
                                <input type="text" name="username" value="{{ newuser.username }}"
                                       placeholder="Tên đăng nhập" required
                                       :class="{ do: !sign_up.checkUserName, xanh:sign_up.checkUserName}">
                                <input type="email" name="email" value="{{ newuser.email }}" required
                                       :class="{ do: !sign_up.checkEmail, xanh:sign_up.checkEmail}"
                                       @input="checkEmail_func" placeholder="Email">
                                <input class="chia" type="password" name="password1"
                                       value="{{ password.password1 }}"
                                       required
                                       :class="{ do: !sign_up.checkPassword , xanh:sign_up.checkPassword}"
                                       autocomplete="on" @input="checkPassword_func"
                                       placeholder="Mật khẩu">
                                <input class="chia" type="password" name="password2"
                                       value="{{ password.password2 }}"
                                       required
                                       :class="{ do: !sign_up.checkPassword, xanh:sign_up.checkPassword}"
                                       autocomplete="on" @input="checkPassword_func"
                                       placeholder="Nhập lại mật khẩu">
                                <input class="chia" type="date" name="birthday" value="{{ newuser.birthday }}"
                                       required
                                       placeholder="Ngày sinh">
                                <select class="chia" name="gender" value="{{ newuser.gender }} required">
                                    <option value="Nam">Nam</option>
                                    <option value="Nu">Nữ</option>
                                </select>
                                {% for i in err %}
                                    <h4 class="my-4  thong_bao"> {{ i }}</h4>
                                {% endfor %}
                                <button class="button" type="submit">Đăng Kí ngay</button>
                            </form>

                        </div>
                        <img src="{% static 'images/cryptocurrency.png' %}" alt="...">
                    </div>
                </div>
            </transition>
        </div>
    </transition>
</div>


<script src="{% static 'home/javascript/login.js' %}"></script>
</body>
</html>

templates/home/lacx.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>

<div class="container">
    {% for i in data %}
    <div class="card m-5">
        <a href="{{ i.image }}" target="_blank"><img src="{{ i.image }}" class="card-img-top" alt="..."></a>
        <div class="card-body">
            <h5 class="card-title">{{ i.title }}</h5>
            <p class="card-text">{{ i.abstract }}</p>
            <p class="card-text"><small class="text-muted">{{ i.content }}</small></p>
        </div>

    </div>
{% endfor %}
</div>



</body>
</html>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ"
        crossorigin="anonymous"></script>